const WHITE = '#FFFFFF';
const BLACK = '#000000';

const PRIMARY_MAIN  = '#2196F3';
const PRIMARY_LIGHT = '#E3F2FD';
const PRIMARY_DARK  = '#1769AA';
const PRIMARY_TEXT  = WHITE;

const SECONDARY_MAIN = '#F50057';
const SECONDARY_DARK = '#AB003C';

export default {
    WHITE,
    BLACK,
    PRIMARY_MAIN,
    PRIMARY_TEXT,
    PRIMARY_LIGHT,
    PRIMARY_DARK,
    SECONDARY_MAIN,
    SECONDARY_DARK
};
