# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeBoilerplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Pods for ReactNativeBoilerplate
  pod 'Fabric'
  pod 'Crashlytics'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

end
