# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv'
Dotenv.load('../.env')

default_platform(:ios)

platform :ios do
  desc "Build App and push a it to Fabric"
  lane :fabric do
    update_app_identifier(
      xcodeproj: ENV['APP_NAME'] + ".xcodeproj",
      plist_path: ENV['APP_NAME'] + "/Info.plist",
      app_identifier: ENV['BUNDLE_ID']
    )
    # match(type: "adhoc")
    register_devices(devices_file: "devices.txt")
    sync_code_signing(force_for_new_devices: true, type: "adhoc")
    increment_build_number
    build_app(scheme: ENV['APP_NAME'])
    crashlytics(
      api_token: ENV['CRASHLITICS_API_TOKEN'],
      build_secret: ENV['CRASHLITICS_BUILD_SECRET'],
      emails: ENV['CRASHLITICS_EMAILS']
    )

  end
end
