# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

file = File.read('../../appconfig.json')
config = JSON.parse(file)

default_platform(:ios)

platform :ios do
  desc "Build App and push a it to Fabric"
  lane :fabric do
    match(type: "adhoc")
    # register_devices(devices_file: "devices.txt")
    # sync_code_signing(force_for_new_devices: true, type: "adhoc")
    # increment_build_number
    # build_app(scheme: config['ios']['app_name'])
    # crashlytics(
    #  api_token: config['ios']['crashlytics_api_token'],
    #  build_secret: config['ios']['crashlytics_build_secret'],
    #  emails: config['ios']['crashlytics_emails']
    # )

  end
end
